services:
  ds-hotspot:
    image: ghcr.io/sdhemily/ds-hotspot:latest
    container_name: ds-hotspot
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      UPLINK_IFACE: eth0
      HOTSPOT_IFACE: wlan0
      # This is an example config and will most likely NOT work for your adapter
      # This has been configured for a Realtek RTL8188FU chipset.
      # Interface is automatically set to HOTSPOT_IFACE so there is no need to include it.
      HOSTAPD_CONF: |
        driver=nl80211

        ssid=DS-Hotspot
        wep_default_key=0
        wep_key0=112233445566778899aabbccdd

        channel=6
        wmm_enabled=0
        auth_algs=1
        ignore_broadcast_ssid=0
        max_num_sta=1
    devices: 
      - /dev/rfkill:/dev/rfkill
    restart: unless-stopped
