# This is an example hostapd.conf and will most likely NOT work for your wireless adapter
# It has been configured for a Realtek RTL8188FU chipset.
# You will likely need to change most of the options depending on your adapter, driver and network conditions.
# It is recommended to configure this file for your specific adapter.

interface=wlan0
driver=nl80211

ssid=DS-Hotspot
wep_default_key=0
wep_key0=112233445566778899aabbccdd

hw_mode=b
channel=6
wmm_enabled=0
auth_algs=1
ignore_broadcast_ssid=0
max_num_sta=1
macaddr_acl=1
accept_mac_file=/etc/hostapd/accept